### ISSUE TITLE
06_tables.txt hangs because of recent rakudo Nil change

### ISSUE THREAD

**Issue by jdv** [tony-o/perl6-html-parser-xml#7]
Below seems to bandaid it.  Not sure if there is a better fix.

[jdv@wieldy t]$ git diff 
diff --git a/t/06_tables.t b/t/06_tables.t
index 6d82ad4..8a60de2 100644
--- a/t/06_tables.t
+++ b/t/06_tables.t
@@ -22,6 +22,7 @@ sub traverse($doc) {
         take $node;
 
         for $node.?nodes -> $child {
+            next if $child ~~ Nil;
             helper($child);
         }
     }
[jdv@wieldy t]$

**Comment by tony-o** [comment]
thanks for the testing ^ fixed with b8223fa
